import {
  defineConfig,
  presetAttributify,
  presetTypography,
  presetWebFonts,
  transformerDirectives,
  transformerVariantGroup,
  presetUno,
} from 'unocss'

export default defineConfig({
  presets: [presetUno(), presetAttributify(), presetTypography(), presetWebFonts()],
  transformers: [transformerDirectives(), transformerVariantGroup()],
  rules: [
    ['bg-error', { 'background-color': 'var(--bg-error)' }],
    ['bg-error-hover', { 'background-color': 'var(--bg-error-hover)' }],
    ['border-error', { 'border-color': 'var(--border-error)' }],
    ['border-error-hover', { 'border-color': 'var(--border-error-hover)' }],
    ['text-error', { color: 'var(--text-error)' }],
    ['text-errorhover', { color: 'var(--text-errorhover)' }],
    ['text-erroractive', { color: 'var(--text-erroractive)' }],
    ['bg-success', { 'background-color': 'var(--bg-success)' }],
    ['bg-success-hover', { 'background-color': 'var(--bg-success-hover)' }],
    ['border-success', { 'border-color': 'var(--border-success)' }],
    ['border-success-hover', { 'border-color': 'var(--border-success-hover)' }],
    ['text-success', { color: 'var(--text-success)' }],
    ['text-successhover', { color: 'var(--text-successhover)' }],
    ['text-successactive', { color: 'var(--text-successactive)' }],
    ['bg-info', { 'background-color': 'var(--bg-info)' }],
    ['bg-info-hover', { 'background-color': 'var(--bg-info-hover)' }],
    ['border-info', { 'border-color': 'var(--border-info)' }],
    ['border-info-hover', { 'border-color': 'var(--border-info-hover)' }],
    ['text-info', { color: 'var(--text-info)' }],
    ['text-infohover', { color: 'var(--text-infohover)' }],
    ['text-infoactive', { color: 'var(--text-infoactive)' }],
    ['bg-warning', { 'background-color': 'var(--bg-warning)' }],
    ['bg-warning-hover', { 'background-color': 'var(--bg-warning-hover)' }],
    ['border-warning', { 'border-color': 'var(--border-warning)' }],
    ['border-warning-hover', { 'border-color': 'var(--border-warning-hover)' }],
    ['text-warning', { color: 'var(--text-warning)' }],
    ['text-warninghover', { color: 'var(--text-warninghover)' }],
    ['text-warningactive', { color: 'var(--text-warningactive)' }],
    ['bg-primary', { 'background-color': 'var(--bg-primary)' }],
    ['bg-primary-hover', { 'background-color': 'var(--bg-primary-hover)' }],
    ['border-primary', { 'border-color': 'var(--border-primary)' }],
    ['border-primary-hover', { 'border-color': 'var(--border-primary-hover)' }],
    ['text-primary', { color: 'var(--text-primary)' }],
    ['text-primaryhover', { color: 'var(--text-primaryhover)' }],
    ['text-primaryactive', { color: 'var(--text-primaryactive)' }],
    ['text-regular', { color: 'var(--text-regular)' }],
    ['text-secondary', { color: 'var(--text-secondary)' }],
    ['text-tertiary', { color: 'var(--text-tertiary)' }],
    ['text-quaternary', { color: 'var(--text-quaternary)' }],
    ['bg-layout', { 'background-color': 'var(--bg-layout)' }],
    ['bg-container', { 'background-color': 'var(--bg-container)' }],
    ['bg-elevated', { 'background-color': 'var(--bg-elevated)' }],
    ['bg-spotlight', { 'background-color': 'var(--bg-spotlight)' }],
    ['border-regular', { 'border-color': 'var(--border-regular)' }],
    ['border-secondary', { 'border-color': 'var(--border-secondary)' }],
    ['drag', { '-webkit-app-region': 'var(--drag)' }],
    ['no-drag', { '-webkit-app-region': 'var(--no-drag)' }],
    ['bg-primary-active', { 'background-color': 'var(--bg-primary-active)' }],
  ],
})
