/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const BOTH: typeof import('../main-process/utils/ipc')['BOTH']
  const BrowserWindow: typeof import('electron')['BrowserWindow']
  const HTML_URL: typeof import('../main-process/utils/constants')['HTML_URL']
  const IpcMainEvent: typeof import('electron')['IpcMainEvent']
  const MTR: typeof import('../main-process/utils/ipc')['MTR']
  const RTM: typeof import('../main-process/utils/ipc')['RTM']
  const __dirname__: typeof import('../main-process/utils/constants')['__dirname__']
  const buildWindowUrl: typeof import('../main-process/utils/window')['buildWindowUrl']
  const checkForUpdate: typeof import('../main-process/utils/auto-update')['checkForUpdate']
  const createFrameWindow: typeof import('../main-process/utils/window')['createFrameWindow']
  const createHomeWindow: typeof import('../main-process/windows/home')['createHomeWindow']
  const createLoginWindow: typeof import('../main-process/windows/login')['createLoginWindow']
  const getConf: typeof import('../main-process/utils/setting')['getConf']
  const getLoginWindow: typeof import('../main-process/windows/login')['getLoginWindow']
  const getUserId: typeof import('../main-process/utils/user')['getUserId']
  const ipcMain: typeof import('electron')['ipcMain']
  const resourcePath: typeof import('../main-process/utils/constants')['resourcePath']
  const setConf: typeof import('../main-process/utils/setting')['setConf']
  const setTrayMenu: typeof import('../main-process/utils/menu')['setTrayMenu']
  const setUserId: typeof import('../main-process/utils/user')['setUserId']
  const tempFolderPath: typeof import('../main-process/utils/constants')['tempFolderPath']
  const windowArgs: typeof import('../main-process/utils/window')['windowArgs']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { RTM, BOTH, MTR, OnEventChannels, HandleEventChannels, SendEventChannels } from '../main-process/utils/ipc'
  import('../main-process/utils/ipc')
  // @ts-ignore
  export type { Conf, ConfKey } from '../main-process/utils/setting'
  import('../main-process/utils/setting')
}
